"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import UserAccountShell from "@/components/user-account-shell";
const offers:Record<string,{title:string;seller:string;price:string;category:string;description:string}>={
"commercial-solar-installation":{title:"Commercial Solar Installation",seller:"SunGrid Energy Ltd.",price:"From $6,500",category:"Business Solution",description:"Commercial solar design and installation support for businesses seeking reliable energy infrastructure."},
"ai-customer-support":{title:"AI Customer Support Implementation",seller:"Nova Commerce",price:"From $2,800",category:"Service",description:"Implementation support for scalable AI-assisted customer support workflows."},
"fleet-tracking":{title:"Fleet Tracking & Management",seller:"Vertex Mobility",price:"From $420",category:"Business Solution",description:"Fleet visibility, tracking and management support for commercial operators."},
"growth-marketing":{title:"Growth Marketing Campaign Package",seller:"Nova Commerce",price:"From $1,900",category:"Business Package",description:"A demo marketing package designed to help a business launch and measure a growth campaign."},
"product-design-consultation":{title:"Product Design Consultation",seller:"Maya Okafor Studio",price:"$180/hr",category:"Expert Service",description:"Professional product design consultation for teams developing new products and experiences."}};
export default function MarketplaceOfferPage(){const {slug}=useParams<{slug:string}>();const offer=offers[slug]??offers["commercial-solar-installation"];return <UserAccountShell><main className="min-h-screen bg-[#f7f8fc] p-5 sm:p-8"><div className="mx-auto max-w-4xl"><Link href="/marketplace" className="text-sm font-bold text-purple-700">← Marketplace</Link><section className="mt-5 overflow-hidden rounded-[2rem] border border-slate-200 bg-white"><div className="flex min-h-64 items-end bg-gradient-to-br from-slate-950 via-slate-800 to-purple-900 p-7 text-white"><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-wider">{offer.category}</span></div><div className="p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Demo marketplace offering</p><h1 className="mt-2 text-3xl font-black">{offer.title}</h1><p className="mt-2 text-sm font-semibold text-slate-500">{offer.seller}</p><p className="mt-6 text-sm leading-7 text-slate-600">{offer.description}</p><p className="mt-6 text-2xl font-black">{offer.price}</p><div className="mt-6 flex flex-wrap gap-3"><button className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Request offering →</button><button className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-700">Save</button></div></div></section></div></main></UserAccountShell>}