import Link from "next/link";
import { notFound } from "next/navigation";

const data: Record<string,{name:string;category:string;initials:string;description:string;about:string;location:string;opportunities:Array<[string,string,string]>;posts:Array<[string,string]>;services:string[]}> = {
  "sungrid-energy": {name:"SunGrid Energy Ltd.",category:"Energy & Infrastructure",initials:"SE",description:"Clean-energy infrastructure and distributed solar solutions for businesses and communities.",about:"SunGrid Energy develops and delivers practical clean-energy infrastructure, with a focus on reliable distributed solar systems and commercial energy expansion.",location:"Lagos, Nigeria",services:["Commercial Solar Installation","Energy Infrastructure","Solar Expansion Projects"],opportunities:[["Investment","Solar Energy Expansion","$5M target • Energy"],["Marketplace","Commercial Solar Installation","From $6,500"]],posts:[["Company update","SunGrid Energy expands its clean-energy programme."],["Opportunity","The next phase of the Solar Energy Expansion programme is now open for participation."]] },
  "nova-commerce": {name:"Nova Commerce",category:"Technology & Commerce",initials:"NC",description:"Commerce technology, customer experience systems and AI-enabled business solutions.",about:"Nova Commerce builds technology and business solutions designed to improve customer experience, operational efficiency and digital commerce.",location:"Lagos, Nigeria",services:["AI Customer Support","Commerce Technology","Business Solutions"],opportunities:[["Innovation","AI Customer Support Challenge","$25,000 reward"],["Marketplace","AI Customer Support Implementation","From $2,800"]],posts:[["Challenge","Nova Commerce opens an AI customer support challenge."],["Company update","New customer experience solutions are being prepared for the next launch cycle."]] },
  "velo-mobility": {name:"Velo Mobility",category:"Mobility & Automotive",initials:"VM",description:"Mobility products, services and growth programmes connecting transport businesses with new markets.",about:"Velo Mobility works across mobility products, services and commercial growth programmes.",location:"Lagos, Nigeria",services:["Mobility Products","Marketing Campaigns","Fleet Solutions"],opportunities:[["Marketing","New Product Launch Campaign","$40,000 budget"],["Marketplace","Fleet Tracking & Management","From $420"]],posts:[["Campaign","Velo Mobility is preparing a new product launch campaign."],["Company update","The company is expanding its commercial mobility programme."]] },
};

export default async function CompanyProfilePage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const company=data[slug]; if(!company) notFound();
  return <main className="min-h-screen bg-[#f7f8fc] text-slate-950">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/" className="flex items-center"><img src="/acepa-logo-white-transparent-tagline-brighter.png" alt="ACEPA" className="h-12 w-auto object-contain brightness-0 dark:brightness-100"/></Link><div className="flex items-center gap-3"><Link href="/companies" className="hidden sm:inline text-sm font-bold text-slate-600">Companies</Link><Link href="/sign-in" className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700">Sign in</Link><Link href="/sign-up" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Get Started</Link></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10">
      <div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm">
        <div className="h-44 bg-gradient-to-br from-slate-950 via-slate-900 to-purple-900"/>
        <div className="relative px-6 pb-7 sm:px-9"><div className="-mt-12 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-4"><div className="flex h-24 w-24 items-center justify-center rounded-3xl border-4 border-white bg-slate-950 text-2xl font-black text-white shadow-lg">{company.initials}</div><div className="pb-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black sm:text-3xl">{company.name}</h1><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase text-emerald-700">Verified</span></div><p className="mt-1 text-sm font-semibold text-purple-600">{company.category}</p></div></div><div className="flex gap-2"><button className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700">Follow</button><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Share</button></div></div><p className="mt-5 max-w-3xl text-sm leading-7 text-slate-600">{company.description}</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold text-slate-500"><span className="rounded-full bg-slate-100 px-3 py-2">{company.location}</span><span className="rounded-full bg-purple-50 px-3 py-2 text-purple-700">ACEPA company profile</span><span className="rounded-full bg-slate-100 px-3 py-2">Public profile</span></div></div>
      </div>
      <div className="mt-7 grid gap-7 lg:grid-cols-[1.55fr_.65fr]">
        <div className="space-y-7">
          <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">About</p><h2 className="mt-2 text-2xl font-black">About {company.name}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{company.about}</p></section>
          <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Company opportunities</p><h2 className="mt-2 text-2xl font-black">Participate with {company.name}</h2></div><Link href="/dashboard/discover" className="text-xs font-black text-purple-700">Explore all →</Link></div><div className="mt-5 grid gap-4">{company.opportunities.map(([kind,title,meta])=><div key={title} className="rounded-2xl border border-slate-200 p-5"><span className="rounded-full bg-purple-50 px-3 py-1 text-[10px] font-black uppercase text-purple-700">{kind}</span><h3 className="mt-3 text-lg font-black">{title}</h3><p className="mt-1 text-sm text-slate-500">{meta}</p><Link href={kind==="Marketplace" ? "/marketplace" : "/dashboard/discover"} className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2 text-xs font-bold text-white">{kind==="Marketplace" ? "View in Marketplace" : "View opportunity"}</Link></div>)}</div></section>
          <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Company feed</p><h2 className="mt-2 text-2xl font-black">Latest from {company.name}</h2></div><Link href="/feed" className="text-xs font-black text-purple-700">Open Feed →</Link></div><div className="mt-5 divide-y divide-slate-200">{company.posts.map(([k,t])=><Link key={t} href="/feed" className="block py-5 first:pt-0 last:pb-0 hover:bg-slate-50"><p className="text-[10px] font-black uppercase tracking-wider text-purple-600">{k}</p><p className="mt-2 font-bold">{t}</p><p className="mt-2 text-xs text-slate-400">Open this company's activity in ACEPA Feed →</p></Link>)}</div></section>
          <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Marketplace</p><h2 className="mt-2 text-2xl font-black">Offerings from this company</h2><p className="mt-2 text-sm text-slate-500">These offerings live in the shared ACEPA Marketplace; this company profile simply surfaces them.</p><Link href="/marketplace" className="mt-5 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Open ACEPA Marketplace →</Link></section>
        </div>
        <aside className="space-y-5"><div className="rounded-3xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Products & services</p><div className="mt-4 space-y-2">{company.services.map(s=><div key={s} className="rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold">{s}</div>)}</div></div><div className="rounded-3xl bg-purple-50 p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-700">Work with this company</p><p className="mt-2 text-sm leading-6 text-slate-600">Explore opportunities, marketplace offerings and company activity through ACEPA.</p><Link href="/dashboard/discover" className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white">Explore opportunities →</Link></div></aside>
      </div>
    </div>
  </main>;
}
