"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function SettingsPage(){
 const router=useRouter(); const[email,setEmail]=useState(""); const[appearance,setAppearance]=useState("system"); const[emailNotifications,setEmailNotifications]=useState(true); const[opportunityNotifications,setOpportunityNotifications]=useState(true); const[activityNotifications,setActivityNotifications]=useState(true); const[marketingNotifications,setMarketingNotifications]=useState(false); const[saving,setSaving]=useState(false); const[message,setMessage]=useState("");
 useEffect(()=>{loadSettings()},[]);
 async function loadSettings(){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/sign-in?next=/settings");return}setEmail(user.email??"");const{data}=await supabase.from("user_preferences").select("*").eq("user_id",user.id).maybeSingle();if(data){setAppearance(data.appearance);setEmailNotifications(data.email_notifications);setOpportunityNotifications(data.opportunity_notifications);setActivityNotifications(data.activity_notifications);setMarketingNotifications(data.marketing_notifications)}}
 async function save(){setSaving(true);setMessage("");const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/sign-in?next=/settings");return}const{error}=await supabase.from("user_preferences").upsert({user_id:user.id,appearance,email_notifications:emailNotifications,opportunity_notifications:opportunityNotifications,activity_notifications:activityNotifications,marketing_notifications:marketingNotifications});setMessage(error?error.message:"Settings saved successfully.");setSaving(false)}
 return <main className="min-h-screen bg-[#f7f8fc] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-5xl items-center justify-between px-5 sm:px-8"><Link href="/dashboard" className="flex items-center"><img src="/acepa-logo-white-transparent-tagline-brighter.png" alt="ACEPA — People, Opportunities, Progress" className="h-12 w-auto object-contain brightness-0"/></Link><Link href="/profile" className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white hover:bg-purple-700">Profile</Link></div></header>
 <div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:py-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-purple-600">Account</p><h1 className="mt-2 text-3xl font-black tracking-[-0.04em] sm:text-4xl">Settings</h1><p className="mt-2 text-sm text-slate-500">Manage your ACEPA preferences and account experience.</p>
 <div className="mt-8 space-y-6"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-black">Account information</h2><p className="mt-2 text-sm text-slate-500">Your sign-in email is currently <span className="font-semibold text-slate-700">{email}</span>.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/forgot-password" className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50">Change password</Link><span className="rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold text-slate-500">Verification status: Not yet verified</span></div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-black">Appearance</h2><p className="mt-2 text-sm text-slate-500">Choose how ACEPA should look on your devices.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{["light","dark","system"].map(item=><button key={item} onClick={()=>setAppearance(item)} className={"rounded-2xl border px-4 py-4 text-left text-sm font-bold capitalize transition "+(appearance===item?"border-purple-500 bg-purple-50 text-purple-700":"border-slate-200 hover:bg-slate-50")}>{item==="system"?"Automatic / System":item}</button>)}</div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-black">Notifications</h2><div className="mt-5 divide-y divide-slate-100">{[["Email notifications","Receive important ACEPA account messages by email",emailNotifications,setEmailNotifications],["Opportunity notifications","Get updates about opportunities relevant to you",opportunityNotifications,setOpportunityNotifications],["Activity notifications","Get updates about your participations and activities",activityNotifications,setActivityNotifications],["Product and marketing","Receive occasional ACEPA product and marketing updates",marketingNotifications,setMarketingNotifications]].map(([title,description,value,setValue])=><div key={title as string} className="flex items-center justify-between gap-5 py-4"><div><p className="text-sm font-bold">{title as string}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description as string}</p></div><button onClick={()=> (setValue as (v:boolean)=>void)(!(value as boolean))} className={"relative h-7 w-12 shrink-0 rounded-full transition "+(value?"bg-slate-950":"bg-slate-200")} aria-label={"Toggle "+title}><span className={"absolute top-1 h-5 w-5 rounded-full bg-white shadow transition "+(value?"left-6":"left-1")}/></button></div>)}</div></section>
 {message&&<p className="rounded-2xl bg-white px-5 py-4 text-sm font-semibold text-slate-700 shadow-sm">{message}</p>}<div className="flex justify-end"><button onClick={save} disabled={saving} className="rounded-xl bg-slate-950 px-6 py-3 text-sm font-bold text-white hover:bg-purple-700 disabled:opacity-60">{saving?"Saving...":"Save settings"}</button></div></div></div></main>;
}
