"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function SettingsPage(){
 const router=useRouter(); const[email,setEmail]=useState(""); const[appearance,setAppearance]=useState("system"); const[systemDark,setSystemDark]=useState(false); const[emailNotifications,setEmailNotifications]=useState(true); const[opportunityNotifications,setOpportunityNotifications]=useState(true); const[activityNotifications,setActivityNotifications]=useState(true); const[marketingNotifications,setMarketingNotifications]=useState(false); const[saving,setSaving]=useState(false); const[message,setMessage]=useState("");
 useEffect(()=>{loadSettings(); const media=window.matchMedia("(prefers-color-scheme: dark)"); const sync=()=>setSystemDark(media.matches); sync(); media.addEventListener("change",sync); return()=>media.removeEventListener("change",sync)},[]);
 async function loadSettings(){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/sign-in?next=/settings");return}setEmail(user.email??"");const{data}=await supabase.from("user_preferences").select("*").eq("user_id",user.id).maybeSingle();if(data){setAppearance(data.appearance);setEmailNotifications(data.email_notifications);setOpportunityNotifications(data.opportunity_notifications);setActivityNotifications(data.activity_notifications);setMarketingNotifications(data.marketing_notifications)}}
 const dark=appearance==="dark" || (appearance==="system" && systemDark); const surface=dark?"bg-slate-950 text-slate-100":"bg-[#f7f8fc] text-slate-950"; const card=dark?"border-slate-800 bg-slate-900":"border-slate-200 bg-white"; const muted=dark?"text-slate-400":"text-slate-500"; const divider=dark?"divide-slate-800":"divide-slate-100"; const inputHover=dark?"hover:bg-slate-800":"hover:bg-slate-50"; const selected=dark?"border-purple-400 bg-purple-950/50 text-purple-300":"border-purple-500 bg-purple-50 text-purple-700"; const buttonDark=dark?"bg-white text-slate-950 hover:bg-purple-300":"bg-slate-950 text-white hover:bg-purple-700"; async function save(){setSaving(true);setMessage("");const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/sign-in?next=/settings");return}const{error}=await supabase.from("user_preferences").upsert({user_id:user.id,appearance,email_notifications:emailNotifications,opportunity_notifications:opportunityNotifications,activity_notifications:activityNotifications,marketing_notifications:marketingNotifications});setMessage(error?error.message:"Settings saved successfully.");setSaving(false)}
 return <main className={"min-h-screen "+surface}><header className={"border-b "+(dark?"border-slate-800 bg-slate-900":"border-slate-200 bg-white")}><div className="mx-auto flex h-20 max-w-5xl items-center justify-between px-5 sm:px-8"><Link href="/dashboard" className="flex items-center"><img src="/acepa-logo-white-transparent-tagline-brighter.png" alt="ACEPA — People, Opportunities, Progress" className={"h-12 w-auto object-contain "+(dark?"":"brightness-0")}/></Link><Link href="/profile" className={"rounded-xl px-4 py-2 text-sm font-bold "+buttonDark}>Profile</Link></div></header>
 <div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:py-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-purple-600">Account</p><h1 className="mt-2 text-3xl font-black tracking-[-0.04em] sm:text-4xl">Settings</h1><p className={"mt-2 text-sm "+muted}>Manage your ACEPA preferences and account experience.</p>
 <div className="mt-8 space-y-6"><section className={"rounded-3xl border p-6 shadow-sm sm:p-8 "+card}><h2 className="text-xl font-black">Account information</h2><p className={"mt-2 text-sm "+muted}>Your sign-in email is currently <span className={dark?"font-semibold text-slate-200":"font-semibold text-slate-700"}>{email}</span>.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/forgot-password" className={"rounded-xl border px-4 py-3 text-sm font-bold "+(dark?"border-slate-700 text-slate-200 hover:bg-slate-800":"border-slate-200 text-slate-700 hover:bg-slate-50")}>Change password</Link><span className={"rounded-xl px-4 py-3 text-sm font-bold "+(dark?"bg-slate-800 text-slate-400":"bg-slate-50 text-slate-500")}>Verification status: Not yet verified</span></div></section>
 <section className={"rounded-3xl border p-6 shadow-sm sm:p-8 "+card}><h2 className="text-xl font-black">Appearance</h2><p className={"mt-2 text-sm "+muted}>Choose how ACEPA should look on your devices.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{["light","dark","system"].map(item=><button key={item} onClick={()=>setAppearance(item)} className={"rounded-2xl border px-4 py-4 text-left text-sm font-bold capitalize transition "+(appearance===item?selected:(dark?"border-slate-700 hover:bg-slate-800":"border-slate-200 hover:bg-slate-50"))}>{item==="system"?"Automatic / System":item}</button>)}</div></section>
 <section className={"rounded-3xl border p-6 shadow-sm sm:p-8 "+card}><h2 className="text-xl font-black">Notifications</h2><div className={"mt-5 divide-y "+divider}>{[["Email notifications","Receive important ACEPA account messages by email",emailNotifications,setEmailNotifications],["Opportunity notifications","Get updates about opportunities relevant to you",opportunityNotifications,setOpportunityNotifications],["Activity notifications","Get updates about your participations and activities",activityNotifications,setActivityNotifications],["Product and marketing","Receive occasional ACEPA product and marketing updates",marketingNotifications,setMarketingNotifications]].map(([title,description,value,setValue])=><div key={title as string} className="flex items-center justify-between gap-5 py-4"><div><p className="text-sm font-bold">{title as string}</p><p className={"mt-1 text-xs leading-5 "+muted}>{description as string}</p></div><button onClick={()=> (setValue as (v:boolean)=>void)(!(value as boolean))} className={"relative h-7 w-12 shrink-0 rounded-full transition "+(value?(dark?"bg-purple-500":"bg-slate-950"):(dark?"bg-slate-700":"bg-slate-200"))} aria-label={"Toggle "+title}><span className={"absolute top-1 h-5 w-5 rounded-full bg-white shadow transition "+(value?"left-6":"left-1")}/></button></div>)}</div></section>
 {message&&<p className={"rounded-2xl px-5 py-4 text-sm font-semibold shadow-sm "+(dark?"bg-slate-900 text-slate-200":"bg-white text-slate-700")}>{message}</p>}<div className="flex justify-end"><button onClick={save} disabled={saving} className={"rounded-xl px-6 py-3 text-sm font-bold disabled:opacity-60 "+buttonDark}>{saving?"Saving...":"Save settings"}</button></div></div></div></main>;
}
