"use client";

import Link from "next/link";
import { UserAccountActions } from "@/components/user-account-top-nav";
import UserAccountShell from "@/components/user-account-shell";

const opportunityCards = [
  { type: "Investment", title: "Solar Energy Expansion", company: "SunGrid Energy Ltd.", location: "Lagos", amount: "$5,000,000", detail: "Scale clean energy infrastructure across underserved communities." },
  { type: "Innovation", title: "Smart Retail Innovation Challenge", company: "Nexa Retail Group", location: "Abuja", amount: "$250,000", detail: "Build practical technology that improves the retail experience." },
  { type: "Marketing", title: "Product Launch Campaign", company: "Urbanova Consumer Brands", location: "Port Harcourt", amount: "$75,000", detail: "Help take a new consumer product to its next market." },
];

export default function DashboardPage() {
  return (
    <UserAccountShell>
      <main className="min-h-screen bg-[#f7f8fc] text-slate-950">
        <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="flex h-20 items-center justify-between px-5 sm:px-8 lg:px-10"><div className="lg:hidden" /><div className="hidden lg:block"><p className="text-xs font-semibold text-slate-400">ACEPA WORKSPACE</p><p className="mt-1 text-black text-sm font-bold">Personal dashboard</p></div><UserAccountActions /></div></header>
        <div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10">
          <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 text-white shadow-xl"><div className="grid min-h-[430px] lg:grid-cols-[1.15fr_0.85fr]"><div className="relative z-10 flex items-center p-7 sm:p-9 lg:p-11"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.22em] text-purple-300">Welcome to ACEPA</p><h1 className="mt-4 text-3xl font-black tracking-[-0.05em] sm:text-4xl lg:text-5xl">Create value. Find opportunity. Make progress.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/65 sm:text-base">Your personal space for discovering opportunities, participating in meaningful projects, tracking your activities, and building your progress across ACEPA.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/dashboard/discover" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-purple-50">Discover opportunities →</Link><Link href="#opportunities" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-bold text-white transition hover:bg-white/10">View recommendations</Link></div></div></div><div className="relative min-h-[260px] lg:min-h-0"><img src="/acepa-hero-3.jpg" alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/45 to-transparent lg:from-slate-950 lg:via-slate-950/15 lg:to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/45 via-transparent to-slate-950/10" /></div></div></section>
          <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Portfolio", "$0.00", "Your active investment value"],["Opportunities", "0", "Active participations"],["Earnings", "$0.00", "Earnings through ACEPA"],["Activity", "0", "Items requiring attention"]].map(([label, value, description]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">{label}</p><p className="mt-3 text-3xl font-black tracking-[-0.04em]">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{description}</p></div>)}</section>
          <section className="mt-10 grid gap-7 xl:grid-cols-[1.5fr_0.75fr]"><div id="opportunities" className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-purple-600">For you</p><h2 className="mt-2 text-2xl font-black tracking-[-0.04em]">Recommended opportunities</h2><p className="mt-2 text-sm text-slate-500">Explore ways to invest, create, collaborate, contribute, and earn.</p></div><Link href="/dashboard/discover" className="hidden text-sm font-bold text-slate-700 hover:text-purple-600 sm:block">See all →</Link></div><div className="mt-6 grid gap-4">{opportunityCards.map((card) => <article key={card.title} className="group rounded-2xl border border-slate-200 p-5 transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex rounded-full bg-purple-50 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-purple-700">{card.type}</span><h3 className="mt-3 text-lg font-black tracking-[-0.025em]">{card.title}</h3><p className="mt-1 text-sm font-semibold text-slate-600">{card.company}</p></div><p className="text-sm font-black">{card.amount}</p></div><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">{card.detail}</p><div className="mt-4 flex items-center justify-between gap-3 text-xs text-slate-400"><span>{card.location}</span><button className="font-bold text-slate-800 transition group-hover:text-purple-600">Explore opportunity →</button></div></article>)}</div></div>
            <div className="space-y-7"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-purple-600">Your journey</p><h2 className="mt-2 text-2xl font-black tracking-[-0.04em]">From discovery to progress</h2><div className="mt-6 space-y-4">{[["01","Discover","Find opportunities that match your interests."],["02","Participate","Invest, contribute, collaborate, create or work."],["03","Track","Follow activity, milestones and updates."],["04","Progress","Complete opportunities and build your record."]].map(([number,title,description]) => <div key={number} className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-[10px] font-black text-slate-500">{number}</span><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div></div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Recent activity</p><div className="mt-5 rounded-2xl bg-slate-50 p-5 text-center"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-white text-lg shadow-sm">◷</div><p className="mt-3 text-sm font-bold">Your activity will appear here</p><p className="mt-1 text-xs leading-5 text-slate-500">Once you participate in opportunities, your latest actions and updates will be shown here.</p></div></div></div>
          </section>
          <section className="mt-7 rounded-3xl border border-purple-100 bg-purple-50/60 p-6 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-purple-600">Keep exploring</p><h2 className="mt-2 text-xl font-black tracking-[-0.03em]">There is more to discover on ACEPA.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Browse investment, innovation, marketing, business, collaboration, expert and career opportunities.</p></div><Link href="/dashboard/discover" className="shrink-0 rounded-xl bg-slate-950 px-5 py-3 text-center text-sm font-bold text-white transition hover:bg-purple-700">Explore Discover →</Link></div></section>
        </div>
      </main>
    </UserAccountShell>
  );
}
