"use client";

import Link from "next/link";
import { UserAccountActions } from "@/components/user-account-top-nav";
import UserAccountShell from "@/components/user-account-shell";

const units=[
  {name:"KFXT Investment Units",status:"ACTIVE",detail:"5 units • Current value $5,680 • +13.60%",href:"/investments/demo-investment-sungrid",action:"View investment performance →"},
  {name:"KAIDG Investment Units",status:"OPEN",detail:"1 unit minimum • $1,000 demo unit value",href:"/investment-units/kaidg",action:"View investment details →"},
];

const explore=[
  ["Investment","Invest in projects and products","/discover/investment"],
  ["Innovation","Provide ideas and solutions","/discover/innovation"],
  ["Marketing","Promote products, brands and campaigns","/discover/marketing"],
  ["Business","Find and grow commercial opportunities","/business"],
  ["Collaboration","Build partnerships and work together","/discover/collaboration"],
  ["Experts","Find or offer professional expertise","/discover/experts"],
  ["Careers & Jobs","Discover jobs and career opportunities","/discover/careers-jobs"],
  ["Idea Proposals","Submit and protect your ideas","/proposals"],
];

const marketplace=[
  ["Commercial Solar Installation","SunGrid Energy Ltd.","From $6,500","/marketplace/commercial-solar-installation"],
  ["AI Customer Support Implementation","Nova Commerce","From $2,800","/marketplace/ai-customer-support"],
  ["Fleet Tracking & Management","Vertex Mobility","From $420","/marketplace/fleet-tracking"],
];

const recommendations=[
  ["Investment","Solar Energy Expansion","SunGrid Energy Ltd.","$5M target • Lagos • Energy","/discover/opportunities/solar-energy-expansion"],
  ["Innovation","AI Customer Support Challenge","Nova Commerce","$25,000 reward • Lagos • Technology","/discover/opportunities/smart-retail-challenge"],
  ["Marketing","New Product Launch Campaign","Velo Mobility","$40,000 budget • Lagos • Automotive","/discover/opportunities/product-launch-campaign"],
];

const news=[
  ["COMPANY UPDATE","SunGrid Energy expands its clean-energy programme","A new opportunity is now available for people interested in participating in the next phase."],
  ["OPPORTUNITY","Nova Commerce opens an AI customer support challenge","Companies can publish challenges on ACEPA and receive practical solutions from participants."],
  ["ACEPA","More ways to participate are coming to ACEPA","Follow companies in Feed to stay connected with the activities and opportunities they publish."],
];

export default function DashboardPage(){
 return <UserAccountShell><main className="min-h-screen bg-[#f7f8fc] text-slate-950">
  <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="flex h-20 items-center justify-between px-5 sm:px-8 lg:px-10"><div className="hidden lg:block"><p className="text-xs font-semibold text-slate-400">ACEPA WORKSPACE</p><p className="mt-1 text-sm font-bold">Personal dashboard</p></div><UserAccountActions/></div></header>
  <div className="mx-auto w-full px-5 py-8 sm:px-8 lg:px-10 lg:py-10">
   <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 text-white shadow-xl"><div className="grid min-h-[430px] lg:grid-cols-[1.15fr_0.85fr]"><div className="relative z-10 flex items-center p-7 sm:p-9 lg:p-11"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-purple-300">Welcome to ACEPA</p><h1 className="mt-4 text-3xl font-black tracking-[-.05em] sm:text-4xl lg:text-5xl">Create value. Find opportunity. Make progress.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/65 sm:text-base">Discover ways to invest, create, collaborate, work and participate across the ACEPA ecosystem.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/dashboard/discover" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950">Discover opportunities →</Link><Link href="#investment-units" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-bold text-white">ACEPA Best Investment Units</Link></div></div></div><div className="relative min-h-[260px] lg:min-h-0"><img src="/acepa-hero-3.jpg" alt="" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/15 to-transparent"/></div></div></section>

   <section id="investment-units" className="mt-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Unit-based investment</p><h2 className="mt-2 text-2xl font-black">ACEPA Best Investment Units</h2><p className="mt-2 text-sm text-slate-500">Buy units, track value and open the relevant investment experience.</p></div><Link href="/investment-units" className="text-sm font-bold text-purple-700">View all →</Link></div><div className="mt-5 grid gap-4 md:grid-cols-2">{units.map(u=><Link href={u.href} key={u.name} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-purple-200 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-purple-50 px-3 py-1 text-[10px] font-black uppercase text-purple-700">Demo unit</span><h3 className="mt-4 text-lg font-black">{u.name}</h3><p className="mt-2 text-sm text-slate-500">{u.detail}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase text-emerald-700">{u.status}</span></div><p className="mt-5 text-xs font-black text-purple-700">{u.action}</p></Link>)}</div></section>

   <section className="mt-8"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Portfolio","$0.00","Your active investment value"],["Participations","3 demo","Active and completed activity"],["Earnings","$2,900.00","Demo earnings through ACEPA"],["Activity","7","Demo items requiring attention"]].map(([l,v,d])=><Link href={l==="Portfolio"?"/investments":l==="Earnings"?"/earnings":l==="Participations"?"/participations":"/activity"} key={l} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:border-purple-200"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">{l}</p><p className="mt-3 text-3xl font-black">{v}</p><p className="mt-2 text-xs leading-5 text-slate-500">{d}</p></Link>)}</div></section>

   <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Overview</p><h2 className="mt-2 text-2xl font-black">Your overview</h2><p className="mt-2 text-sm text-slate-500">A quick view of your ACEPA progress and portfolio direction.</p></div><Link href="/investments" className="text-sm font-bold text-purple-700">View portfolio →</Link></div><div className="mt-6 grid gap-6 lg:grid-cols-[.65fr_1fr]"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Total earned</p><p className="mt-2 text-3xl font-black">$2,900.00</p><p className="mt-2 text-sm text-slate-500">Demo total across eligible activity.</p></div><div className="flex h-28 items-end gap-2">{[28,35,31,48,43,59,66,75].map((h,i)=><div key={i} className="h-full flex-1 rounded-lg bg-slate-100 flex items-end overflow-hidden"><div className="w-full rounded-lg bg-purple-600" style={{height:h+"%"}}/></div>)}</div></div></section>

   <section className="mt-8 rounded-3xl border border-purple-100 bg-purple-50/60 p-6 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Referral program</p><h2 className="mt-2 text-2xl font-black">Build referrals. Earn from qualifying activity.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Demo: 28 people referred • 12 successful referrals • 43% conversion • $1,160 earned at 10% of eligible ACEPA revenue.</p></div><Link href="/referrals" className="rounded-xl bg-slate-950 px-5 py-3 text-center text-sm font-bold text-white">Open referral program →</Link></div></section>

   <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Explore the platform</p><h2 className="mt-2 text-2xl font-black">Explore ACEPA</h2></div><Link href="/dashboard/discover" className="text-sm font-bold text-purple-700">Discover →</Link></div><div className="mt-5 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white">{explore.map(([t,d,h])=><Link key={t} href={h} className="flex items-center justify-between gap-4 p-5 hover:bg-slate-50"><div><p className="font-black">{t}</p><p className="mt-1 text-sm text-slate-500">{d}</p></div><span className="text-xs font-black text-purple-700">Explore →</span></Link>)}</div></section>

   <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Marketplace</p><h2 className="mt-2 text-2xl font-black">Business services, solutions and offers</h2><p className="mt-2 text-sm text-slate-500">Find things you can use, hire, access or engage for your business.</p></div><Link href="/marketplace" className="text-sm font-bold text-purple-700">Open marketplace →</Link></div><div className="mt-5 grid gap-4 md:grid-cols-3">{marketplace.map(([t,c,p,h])=><Link href={h} key={t} className="rounded-3xl border border-slate-200 bg-white p-5 hover:-translate-y-0.5 hover:border-purple-200 hover:shadow-md"><div className="flex h-32 items-end rounded-2xl bg-gradient-to-br from-slate-950 via-slate-800 to-purple-900 p-4 text-white"><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-black uppercase">Demo offering</span></div><h3 className="mt-4 text-lg font-black">{t}</h3><p className="mt-1 text-sm font-semibold text-slate-500">{c}</p><p className="mt-3 font-black">{p}</p><p className="mt-4 text-xs font-black text-purple-700">View offering →</p></Link>)}</div></section>

   <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">For you</p><h2 className="mt-2 text-2xl font-black">Recommended opportunities</h2><p className="mt-2 text-sm text-slate-500">Demo recommendations based on your interests and participation signals.</p></div><Link href="/opportunities" className="text-sm font-bold text-purple-700">See all →</Link></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{recommendations.map(([k,t,c,m,h])=><Link href={h} key={t} className="rounded-3xl border border-slate-200 bg-white p-6 hover:-translate-y-0.5 hover:border-purple-200 hover:shadow-md"><span className="rounded-full bg-purple-50 px-3 py-1 text-[10px] font-black uppercase text-purple-700">{k}</span><h3 className="mt-4 text-lg font-black">{t}</h3><p className="mt-1 text-sm font-semibold text-slate-500">{c}</p><p className="mt-2 text-xs text-slate-400">{m}</p><p className="mt-5 text-xs font-black text-purple-700">Open opportunity →</p></Link>)}</div></section>

   <section className="mt-10 grid gap-7 lg:grid-cols-[1.4fr_.8fr]"><div><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Company activity</p><h2 className="mt-2 text-2xl font-black">Latest from companies</h2></div><Link href="/feed" className="text-sm font-bold text-purple-700">View feed →</Link></div><div className="mt-5 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white">{news.map(([k,t,d])=><Link href="/feed" key={t} className="block p-5 hover:bg-slate-50"><p className="text-[10px] font-black tracking-wider text-purple-600">{k}</p><h3 className="mt-2 font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p><p className="mt-3 text-xs font-black text-purple-700">Open Feed →</p></Link>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-purple-600">Upcoming</p><h2 className="mt-2 text-2xl font-black">Prepare for what is next.</h2><p className="mt-3 text-sm leading-6 text-slate-500">See projects and opportunities that are being reviewed or prepared before they go live.</p><Link href="/projects" className="mt-5 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">View upcoming projects →</Link></div></section>
  </div></main></UserAccountShell>
}